#
# General configuration
#
version: 1.0.{build}

branches:
  except:
    - gh-pages

skip_branch_with_pr: true

#
# Environment configuration
#
image: Visual Studio 2017
configuration: Release

nuget:
  disable_publish_on_pr: true

#
# Build configuration
#
before_build:
  - cmd: npm install bower -g
  - cmd: cd src
  - cmd: dotnet restore
  - cmd: cd Cyberkruz.PublishProfile.Web
  - cmd: bower install
  - cmd: cd ../..

build:
  project: src\Cyberkruz.PublishProfile.sln
  verbosity: minimal
  publish_wap: true

after_build:
  - cmd: dotnet publish src/Cyberkruz.PublishProfile.Web --output %appveyor_build_folder%\dist --configuration Release

#
# Test configuration
#
test_script:
 - cmd: dotnet test src/Cyberkruz.PublishProfile.Web.Tests/Cyberkruz.PublishProfile.Web.Tests.csproj

#
# Artifact configuration
#
artifacts:
  - path: dist
    name: web-app

#
# Deployment configuration
#
deploy:
  - provider: WebDeploy
    server: https://publishprofile-webdeploy.scm.azurewebsites.net:443/msdeploy.axd?site=publishprofile-webdeploy
    website: publishprofile-webdeploy
    username:
      secure: tK5XrVFIJ5+sHYfFbHn/oM1PLKyZ2OZdq04Bh92pE7c=
    password:
      secure: fJxVajoDmOl5O7GNLz0KmUApyD77TDTSF2nradKXHbmMQfFgXBEq8InjZPbWfJm7LaB5oKm637r9yjObgowlHQ==
    ntlm: false
    artifact: web-app
    remove_files: true
    aspnet_core: true
    aspnet_core_force_restart: true
    app_offline: true
    on:
      branch: master
